import test from 'node:test';
import assert from 'node:assert/strict';
import { launch, advance, trajectory, OFFICE_BIN, BEACH_BIN, ORIGIN, STEP, BALL_RADIUS, type Basket, type BallState } from '../lib/game/physics';
const aimedYaw = (bin:Basket)=>Math.atan2(bin.x-ORIGIN.x,ORIGIN.z-bin.z);
function simulate(body:BallState,bin:Basket){const events=[];for(let i=0;i<1500&&!body.settled;i++){const event=advance(body,bin);if(event)events.push(event);}return events;}
for(const [level,bin,power] of [[1,OFFICE_BIN,69],[2,BEACH_BIN,79]] as const){
 test(`Level ${level}: a centered throw enters the opening and scores exactly once`,()=>{const body=launch(power,aimedYaw(bin),42);const events=simulate(body,bin);assert.equal(events.filter(e=>e==='score').length,1);assert.ok(body.inside);assert.ok(body.settled);assert.ok(body.position.y>=BALL_RADIUS);});
 test(`Level ${level}: preview matches live simulation over different powers and angles`,()=>{for(const p of [30,50,69,79,95])for(const angle of [30,42,58])for(const offset of [-.12,0,.12]){const preview=trajectory(p,aimedYaw(bin)+offset,angle,bin);const body=launch(p,aimedYaw(bin)+offset,angle);let liveMake=false;for(let i=0;i<900;i++){const event=advance(body,bin);if(event==='score'){liveMake=true;break;}if(event==='floor'||body.settled)break;}assert.equal(preview.makes,liveMake,`power ${p}, angle ${angle}, offset ${offset}`);}});
}
test('A ball traveling upward through the opening does not score',()=>{const body=launch(20,0,42);body.position={x:OFFICE_BIN.x,y:OFFICE_BIN.height-.25,z:OFFICE_BIN.z};body.velocity={x:0,y:4,z:0};for(let i=0;i<40;i++)assert.notEqual(advance(body,OFFICE_BIN),'score');assert.equal(body.scored,false);});
test('An off-center throw misses rather than snapping into the basket',()=>{const body=launch(69,.23,42);simulate(body,OFFICE_BIN);assert.equal(body.scored,false);assert.equal(body.inside,false);});
test('A downward rim strike bounces upward',()=>{const body=launch(20,0,42);body.position={x:OFFICE_BIN.x+OFFICE_BIN.radius,y:OFFICE_BIN.height+.131,z:OFFICE_BIN.z};body.velocity={x:0,y:-3,z:0};let hit=false;for(let i=0;i<6;i++){if(advance(body,OFFICE_BIN)==='rim')hit=true;}assert.ok(hit);assert.ok(body.velocity.y>0);assert.equal(body.scored,false);});
test('Gravity and drag remain stable when the fixed step is halved',()=>{const a=launch(69,.03,42),b=launch(69,.03,42);for(let i=0;i<180;i++)advance(a,OFFICE_BIN,[],STEP);for(let i=0;i<360;i++)advance(b,OFFICE_BIN,[],STEP/2);assert.ok(Math.hypot(a.position.x-b.position.x,a.position.y-b.position.y,a.position.z-b.position.z)<.035);});
test('Furniture stops the ball and is included in the visible trajectory',()=>{const box={min:{x:-1,y:0,z:1},max:{x:1,y:4,z:1.2}};const prediction=trajectory(69,.03,42,OFFICE_BIN,[box]);assert.equal(prediction.makes,false);const body=launch(69,.03,42);let hit=false;for(let i=0;i<500;i++)if(advance(body,OFFICE_BIN,[box])==='wall')hit=true;assert.ok(hit);assert.equal(body.scored,false);});
